
-- 11. Crear tabla de Turnos (Appointments)
CREATE TABLE IF NOT EXISTS public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id bigint REFERENCES public.services(id) ON DELETE SET NULL,
  service_name text,
  service_image text,
  customer_name text NOT NULL,
  customer_phone text,
  customer_email text,
  description text,
  appointment_date timestamp with time zone NOT NULL,
  status text DEFAULT 'Pendiente',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Turnos admin" ON public.appointments;
CREATE POLICY "Turnos admin" ON public.appointments FOR ALL USING (auth.role() = 'authenticated');
