-- 1. Crear tabla de Productos
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price numeric NOT NULL,
  image text,
  category text,
  description text,
  features text[],
  stock integer DEFAULT 0,
  available boolean DEFAULT true,
  featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- CORRECCIÓN: Agregar columnas si la tabla ya existía sin ellas
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS featured boolean DEFAULT false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock integer DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS available boolean DEFAULT true;

-- 2. Crear tabla de Servicios
CREATE TABLE IF NOT EXISTS public.services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "anchorId" text,
  category text,
  title text,
  description text,
  image text,
  "fullDescription" text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Crear tabla de Ventas
CREATE TABLE IF NOT EXISTS public.sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer text NOT NULL,
  total numeric NOT NULL,
  status text NOT NULL,
  items text[] DEFAULT '{}',
  date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Habilitar Seguridad (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- 5. Limpiar políticas antiguas
DROP POLICY IF EXISTS "Productos publicos" ON public.products;
DROP POLICY IF EXISTS "Productos admin" ON public.products;
DROP POLICY IF EXISTS "Servicios publicos" ON public.services;
DROP POLICY IF EXISTS "Servicios admin" ON public.services;
DROP POLICY IF EXISTS "Ventas admin" ON public.sales;

-- 6. Crear Políticas de Productos
CREATE POLICY "Productos publicos" ON public.products FOR SELECT USING (true);
CREATE POLICY "Productos admin" ON public.products FOR ALL USING (auth.role() = 'authenticated');

-- 7. Crear Políticas de Servicios
CREATE POLICY "Servicios publicos" ON public.services FOR SELECT USING (true);
CREATE POLICY "Servicios admin" ON public.services FOR ALL USING (auth.role() = 'authenticated');

-- 8. Crear Políticas de Ventas
CREATE POLICY "Ventas admin" ON public.sales FOR ALL USING (auth.role() = 'authenticated');

-- 9. Configuración de Storage (Imágenes)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('images', 'images', true) 
ON CONFLICT (id) DO NOTHING;

-- 10. Configuración del Sitio (Hero, Textos, etc.)
CREATE TABLE IF NOT EXISTS public.site_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  value text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.site_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Config publica" ON public.site_config;
CREATE POLICY "Config publica" ON public.site_config FOR SELECT USING (true);

DROP POLICY IF EXISTS "Config admin" ON public.site_config;
CREATE POLICY "Config admin" ON public.site_config FOR ALL USING (auth.role() = 'authenticated');

-- Insertar configuración por defecto para el Hero del Catálogo
INSERT INTO public.site_config (key, value)
VALUES ('catalog_hero_image', 'https://images.pexels.com/photos/100650/pexels-photo-100650.jpeg?auto=compress&cs=tinysrgb&w=1600')
ON CONFLICT (key) DO NOTHING;
